"""
Provider Mapping Definitions — Adapted from provider_7.12 JSON Schema
Matches billing and rendering provider fields from EDI 837 Claims structured JSON.
"""

BILLING_PROVIDER_MAPPING_DEFINITION = {
    "name": "Billing Provider Schema Mapping",
    "mapping_type": "only_mapped",
    "expressions": {
        "ProviderID":                "detail.submitter_NM1_loop.transaction_set_header_NM1[2].billing_provider_id",
        "LastName":                  "detail.submitter_NM1_loop.transaction_set_header_NM1[2].billing_provider_name",
        "FirstName":                 "detail.submitter_NM1_loop.transaction_set_header_NM1[2].first_name",
        "MiddleInitial":             "detail.submitter_NM1_loop.transaction_set_header_NM1[2].middle_name",
        "NPI":                       "detail.submitter_NM1_loop.transaction_set_header_NM1[2].billing_provider_id",
        "TaxonomyCode1":             "detail.submitter_NM1_loop.transaction_set_header_PRV[0].provider_taxonomy_code",
        "HpSpecialtyCode1":          "detail.unmapped",
        "ADVProviderSpecialtyCode1": "detail.unmapped",
        "TaxonomyCode2":             "detail.unmapped",
        "HpSpecialtyCode2":          "detail.unmapped",
        "ADVProviderSpecialtyCode2": "detail.unmapped",
        "TaxonomyCode3":             "detail.unmapped",
        "HpSpecialtyCode3":          "detail.unmapped",
        "ADVProviderSpecialtyCode3": "detail.unmapped",
        "TaxonomyCode4":             "detail.unmapped",
        "HpSpecialtyCode4":          "detail.unmapped",
        "ADVProviderSpecialtyCode4": "detail.unmapped",
        "TaxonomyCode5":             "detail.unmapped",
        "HpSpecialtyCode5":          "detail.unmapped",
        "ADVProviderSpecialtyCode5": "detail.unmapped",
        "PrescribePrivilege":        "detail.unmapped",
        "DEA":                       "detail.unmapped",
        "PayorID":                   "detail.unmapped",
        "Contracted":                "detail.unmapped",
        "ProviderHAI":               "detail.unmapped",
        "HospitalID":                "detail.unmapped",
        "ExcludeFromProviderReporting": "detail.unmapped",
        "AltProvReporting1":         "detail.unmapped",
        "AltProvReporting2":         "detail.unmapped",
        "AltProvReporting3":         "detail.unmapped",
        "AltProvReporting4":         "detail.unmapped",
        "AltProvReporting5":         "detail.unmapped",
        "AltProvReporting6":         "detail.unmapped",
        "AltProvReporting7":         "detail.unmapped",
        "AltProvReporting8":         "detail.unmapped",
        "AltProvReporting9":         "detail.unmapped",
        "AltProvReporting10":        "detail.unmapped",
    }
}

RENDERING_PROVIDER_MAPPING_DEFINITION = {
    "name": "Rendering Provider Schema Mapping",
    "mapping_type": "only_mapped",
    "expressions": {
        "ProviderID":                "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_id",
        "LastName":                  "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_last_name",
        "FirstName":                 "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_first_name",
        "MiddleInitial":             "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_middle_name",
        "NPI":                       "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_id",
        "TaxonomyCode1":             "detail.submitter_NM1_loop.transaction_set_header_PRV[1].provider_taxonomy_code",
        "HpSpecialtyCode1":          "detail.unmapped",
        "ADVProviderSpecialtyCode1": "detail.unmapped",
        "TaxonomyCode2":             "detail.unmapped",
        "HpSpecialtyCode2":          "detail.unmapped",
        "ADVProviderSpecialtyCode2": "detail.unmapped",
        "TaxonomyCode3":             "detail.unmapped",
        "HpSpecialtyCode3":          "detail.unmapped",
        "ADVProviderSpecialtyCode3": "detail.unmapped",
        "TaxonomyCode4":             "detail.unmapped",
        "HpSpecialtyCode4":          "detail.unmapped",
        "ADVProviderSpecialtyCode4": "detail.unmapped",
        "TaxonomyCode5":             "detail.unmapped",
        "HpSpecialtyCode5":          "detail.unmapped",
        "ADVProviderSpecialtyCode5": "detail.unmapped",
        "PrescribePrivilege":        "detail.unmapped",
        "DEA":                       "detail.unmapped",
        "PayorID":                   "detail.unmapped",
        "Contracted":                "detail.unmapped",
        "ProviderHAI":               "detail.unmapped",
        "HospitalID":                "detail.unmapped",
        "ExcludeFromProviderReporting": "detail.unmapped",
        "AltProvReporting1":         "detail.unmapped",
        "AltProvReporting2":         "detail.unmapped",
        "AltProvReporting3":         "detail.unmapped",
        "AltProvReporting4":         "detail.unmapped",
        "AltProvReporting5":         "detail.unmapped",
        "AltProvReporting6":         "detail.unmapped",
        "AltProvReporting7":         "detail.unmapped",
        "AltProvReporting8":         "detail.unmapped",
        "AltProvReporting9":         "detail.unmapped",
        "AltProvReporting10":        "detail.unmapped",
    }
}
