"""
Provider Mapping Definitions — Adapted from provider_7.12 JSON Schema
Matches billing and rendering provider fields from EDI 837 Claims structured JSON.
"""

BILLING_PROVIDER_MAPPING_DEFINITION = {
    "name": "Billing Provider Schema Mapping",
    "mapping_type": "only_mapped",
    "expressions": {
        "ProviderID":                "detail.submitter_NM1_loop.transaction_set_header_NM1[2].billing_provider_id",
        "LastName":                  "detail.submitter_NM1_loop.transaction_set_header_NM1[2].billing_provider_name",
        "FirstName":                 "detail.submitter_NM1_loop.transaction_set_header_NM1[2].first_name",
        "MiddleInitial":             "detail.submitter_NM1_loop.transaction_set_header_NM1[2].middle_name",
        "NPI":                       "detail.submitter_NM1_loop.transaction_set_header_NM1[2].billing_provider_id",
        "TaxonomyCode1":             "detail.submitter_NM1_loop.transaction_set_header_PRV[0].provider_taxonomy_code",
        "HpSpecialtyCode1":          "detail.unmapped",
        "ADVProviderSpecialtyCode1": "detail.unmapped",
        "TaxonomyCode2":             "detail.unmapped",
        "HpSpecialtyCode2":          "detail.unmapped",
        "ADVProviderSpecialtyCode2": "detail.unmapped",
        "TaxonomyCode3":             "detail.unmapped",
        "HpSpecialtyCode3":          "detail.unmapped",
        "ADVProviderSpecialtyCode3": "detail.unmapped",
        "TaxonomyCode4":             "detail.unmapped",
        "HpSpecialtyCode4":          "detail.unmapped",
        "ADVProviderSpecialtyCode4": "detail.unmapped",
        "TaxonomyCode5":             "detail.unmapped",
        "HpSpecialtyCode5":          "detail.unmapped",
        "ADVProviderSpecialtyCode5": "detail.unmapped",
        "PrescribePrivilege":        "detail.unmapped",
        "DEA":                       "detail.submitter_NM1_loop.transaction_set_header_REF_0F.reference_identification",
        "PayorID":                   "detail.submitter_NM1_loop.transaction_set_header_REF_PQ.reference_identification",
        "Contracted":                "detail.unmapped",
        "ProviderHAI":               "detail.unmapped",
        "HospitalID":                "detail.unmapped",
        "ExcludeFromProviderReporting": "detail.unmapped",
        "AltProvReporting1":         "detail.submitter_NM1_loop.transaction_set_header_REF_1A.reference_identification",
        "AltProvReporting2":         "detail.submitter_NM1_loop.transaction_set_header_REF_1B.reference_identification",
        "AltProvReporting3":         "detail.unmapped",
        "AltProvReporting4":         "detail.unmapped",
        "AltProvReporting5":         "detail.unmapped",
        "AltProvReporting6":         "detail.unmapped",
        "AltProvReporting7":         "detail.unmapped",
        "AltProvReporting8":         "detail.unmapped",
        "AltProvReporting9":         "detail.unmapped",
        "AltProvReporting10":        "detail.unmapped",
    }
}

RENDERING_PROVIDER_MAPPING_DEFINITION = {
    "name": "Rendering Provider Schema Mapping",
    "mapping_type": "only_mapped",
    "expressions": {
        "ProviderID":                "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_id",
        "LastName":                  "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_last_name",
        "FirstName":                 "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_first_name",
        "MiddleInitial":             "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_middle_name",
        "NPI":                       "detail.submitter_NM1_loop.transaction_set_header_NM1[5].rendering_provider_id",
        "TaxonomyCode1":             "detail.submitter_NM1_loop.transaction_set_header_PRV[1].provider_taxonomy_code",
        "TaxonomyCode2":             "detail.submitter_NM1_loop.transaction_set_header_PRV[2].provider_taxonomy_code",
        "TaxonomyCode3":             "detail.submitter_NM1_loop.transaction_set_header_PRV[3].provider_taxonomy_code",
        "HpSpecialtyCode1":          "detail.unmapped",
        "ADVProviderSpecialtyCode1": "detail.unmapped",
        "HpSpecialtyCode2":          "detail.unmapped",
        "ADVProviderSpecialtyCode2": "detail.unmapped",
        "HpSpecialtyCode3":          "detail.unmapped",
        "ADVProviderSpecialtyCode3": "detail.unmapped",
        "TaxonomyCode4":             "detail.unmapped",
        "HpSpecialtyCode4":          "detail.unmapped",
        "ADVProviderSpecialtyCode4": "detail.unmapped",
        "TaxonomyCode5":             "detail.unmapped",
        "HpSpecialtyCode5":          "detail.unmapped",
        "ADVProviderSpecialtyCode5": "detail.unmapped",
        "PrescribePrivilege":        "detail.unmapped",
        "DEA":                       "detail.submitter_NM1_loop.transaction_set_header_REF_0F.reference_identification",
        "PayorID":                   "detail.submitter_NM1_loop.transaction_set_header_REF_PQ.reference_identification",
        "Contracted":                "detail.unmapped",
        "ProviderHAI":               "detail.unmapped",
        "HospitalID":                "detail.unmapped",
        "ExcludeFromProviderReporting": "detail.unmapped",
        "AltProvReporting1":         "detail.submitter_NM1_loop.transaction_set_header_REF_1A.reference_identification",
        "AltProvReporting2":         "detail.submitter_NM1_loop.transaction_set_header_REF_1B.reference_identification",
        "AltProvReporting3":         "detail.unmapped",
        "AltProvReporting4":         "detail.unmapped",
        "AltProvReporting5":         "detail.unmapped",
        "AltProvReporting6":         "detail.unmapped",
        "AltProvReporting7":         "detail.unmapped",
        "AltProvReporting8":         "detail.unmapped",
        "AltProvReporting9":         "detail.unmapped",
        "AltProvReporting10":        "detail.unmapped",
    }
}

HIERARCHY_PROVIDER_MAPPING_DEFINITION = {
    "name": "Provider Hierarchy Schema Mapping",
    "mapping_type": "only_mapped",
    "expressions": {
        "PROVIDERID":        "detail.provider_hierarchy_loop.NM1[0].entity_identifier",
        "PROVIDERLASTNAME":  "detail.provider_hierarchy_loop.NM1[0].last_name",
        "PROVIDERNPI":       "detail.provider_hierarchy_loop.NM1[0].npi",
        "LOCATIONADDRESS1":  "detail.provider_hierarchy_loop.N3[0].address_line_1",
        "LOCATIONCITY":      "detail.provider_hierarchy_loop.N4[0].city",
        "LOCATIONSTATE":     "detail.provider_hierarchy_loop.N4[0].state_code",
        "LOCATIONZIP":       "detail.provider_hierarchy_loop.N4[0].zip_code",
        "LOCATIONTIN":       "detail.provider_hierarchy_loop.REF[0].reference_identification",
        "LOCATIONIDTYPE":    "detail.unmapped",
        "LOCATIONID":        "detail.unmapped",
        "LOCATIONDESC":      "detail.unmapped",
        "LOCATIONRANKING":   "detail.unmapped",
        "LOCATIONGROUPID":   "detail.unmapped",
        "COUNTYCODE":        "detail.unmapped",
        "PHONENUMBER":       "detail.unmapped",
        "FAXNUMBER":         "detail.unmapped",
        "CONTACTPERSON":     "detail.unmapped",
        "DONOTCHASE":        "detail.unmapped",
        "TIER2IDTYPE":       "detail.unmapped",
        "TIER2ID":           "detail.unmapped",
        "TIER2DESC":         "detail.unmapped",
        "TIER2ADDRESS1":     "detail.unmapped",
        "TIER2ADDRESS2":     "detail.unmapped",
        "TIER2CITY":         "detail.unmapped",
        "TIER2STATE":        "detail.unmapped",
        "TIER2ZIP":          "detail.unmapped",
        "TIER3IDTYPE":       "detail.unmapped",
        "TIER3ID":           "detail.unmapped",
        "TIER3DESC":         "detail.unmapped",
        "TIER3ADDRESS1":     "detail.unmapped",
        "TIER3ADDRESS2":     "detail.unmapped",
        "TIER3CITY":         "detail.unmapped",
        "TIER3STATE":        "detail.unmapped",
        "TIER3ZIP":          "detail.unmapped",
        "TIER4IDTYPE":       "detail.unmapped",
        "TIER4ID":           "detail.unmapped",
        "TIER4DESC":         "detail.unmapped",
        "TIER4ADDRESS1":     "detail.unmapped",
        "TIER4ADDRESS2":     "detail.unmapped",
        "TIER4CITY":         "detail.unmapped",
        "TIER4STATE":        "detail.unmapped",
        "TIER4ZIP":          "detail.unmapped",
        "STARTDATE":         "detail.unmapped",
        "ENDDATE":           "detail.unmapped"
    }
}
